name: Supersimple Configuration Uploader

description: Upload YAML configuration to Supersimple

inputs:
  account_id:
    description: Supersimple account ID
    required: true
  token:
    description: Supersimple API token
    required: true
  api_url:
    description: Supersimple API URL
    required: false
    default: https://app.supersimple.io
  validate_dangling:
    description: Validate dangling objects in Supersimple
    required: false
    default: "false"
  delete_dangling:
    description: Delete dangling objects in Supersimple
    required: false
    default: "false"
  config_file:
    description: Path to configuration file
    required: false
    default: ./supersimple.yaml

runs:
  using: composite

  steps:
    - shell: bash
      env:
        SUPERSIMPLE_TOKEN: ${{ inputs.token }}
        SUPERSIMPLE_ACCOUNT_ID: ${{ inputs.account_id }}
        SUPERSIMPLE_HOST: ${{ inputs.api_url }}
        SUPERSIMPLE_CONFIG_FILE: ${{ inputs.config_file }}
      run: |
        echo "Uploading $SUPERSIMPLE_CONFIG_FILE:"
        echo "  Account ID: $SUPERSIMPLE_ACCOUNT_ID"
        echo "  Supersimple host: $SUPERSIMPLE_HOST"

        wget -q https://assets.supersimple.io/supersimple-cli/releases/v2.11.0/supersimple-x86_64-linux-gnu
        chmod +x supersimple-x86_64-linux-gnu

        if [ "${{ inputs.validate_dangling }}" = "true" ]; then
          ./supersimple-x86_64-linux-gnu validate $SUPERSIMPLE_CONFIG_FILE --validate-dangling
        else
          ./supersimple-x86_64-linux-gnu validate $SUPERSIMPLE_CONFIG_FILE
        fi

        if [ "${{ inputs.delete_dangling }}" = "true" ]; then
          ./supersimple-x86_64-linux-gnu import $SUPERSIMPLE_CONFIG_FILE --delete-dangling
        else
          ./supersimple-x86_64-linux-gnu import $SUPERSIMPLE_CONFIG_FILE
        fi

        rm supersimple-x86_64-linux-gnu

